### ISSUE TITLE
Implement CLI to bind/unbind RH to MH

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#113]
We need to allow user explicitly bind or unbind RH to/from MH.
For this SS needs a new CLI command like: `subutai [bind|unbind] {MH-fingerprint}`

**Comment by soffokl** [comment]
Adding binding to the CLI for that looks useless. 
It should be configured on RH side before connecting to SS.
And we have configuration file for that https://github.com/subutai-io/subos/wiki/How-to-install-several-peers-within-the-same-LAN

If we have several SS installed within the same LAN, new RH with Agent will not be able to properly connect to any of SS before configuration. 

So adding extra binding looks pointless. Besides it we already have too many binding and since it's human interface we need to keep comfortable.

**Comment by Dilshat** [comment]
This binding would be called after user has approved RH and joined it to MH.
User approves RH and has option (checkbox) to bind RH to MH. Later on when removing RH from SS, unbind binding would be called automatically.

**Comment by soffokl** [comment]
At that moment user should manually bind RH to the SS in the very specific case - if he want to install several Peers within LAN.

If we are adding automatic bind we will have following undefined states:
- If SS became broken user will need to manually unbind and bind all RH instead of just reimport SS. (Number of RH can be big enough)
- If SS unbind RH, what should RH discovery do? It will again send request to undefined SS to be connected. 
- New installed RH in the LAN with several SS do not know which peer it should use. How it should behave in this case?

**Comment by Dilshat** [comment]
I agree that for several RHs (several peers in the same LAN) admin should explicitly configure agent to work with a specific MH.
In case when MH becomes broken, admin should explicitly rebind RH to another MH.
Seems current implementation where by default RH seeks for an available MH, and if configured then goes to a specific RH - is most optimal.

**Comment by Dilshat** [comment]
Closing as no better way is found yet
