### ISSUE TITLE
Remove CDN dependency when using --local switch

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#343]
Currently if --local switch is used, agent still depends on and queries information from CDN.
If there is no Internet, this breaks import operation.

**Comment by amol4anoff** [comment]
When i import template second time with --local, i have the following message:

subutai@subutai:~$ sudo subutai-master import ubuntu14 --local
INFO[2018-02-16 11:40:21] Importing ubuntu14                           
INFO[2018-02-16 11:40:21] ubuntu14 instance exists

**Comment by amol4anoff** [comment]
Ok, done.

sudo subutai-master destroy ubuntu14       
INFO[2018-02-16 11:46:38] Destroying template ubuntu14                 
INFO[2018-02-16 11:46:38] ubuntu14 is destroyed                        
subutai@subutai:~$ sudo subutai-master import ubuntu14 --local
INFO[2018-02-16 11:46:46] Importing ubuntu14                           
WARN[2018-02-16 11:46:46] Skipping file integrity verification since -local flag was passed 
INFO[2018-02-16 11:46:46] Unpacking template ubuntu14                  
INFO[2018-02-16 11:46:48] Installing template ubuntu14
