### ISSUE TITLE
Connectivity issue on initial setup

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#762]
After initial setup of peer, agent has problem connecting to Console. After agent restart problem is gone.

**Comment by AlinaPenkina** [comment]
Test case 1:
1. Brought peer up via CC
2. Logged in Subutai Console. Result RH was online.
![screenshot from 2018-08-28 16-20-28](https://user-images.githubusercontent.com/34295807/44717381-aacfb200-aade-11e8-93c4-92b62ee4ee4c.png)
3. Played with some commands.

est case 1:
1. Brought peer up via Vagrant
2. Logged in Subutai Console. Result RH was online.
3. Played with some commands.

Fixed in Master
