### ISSUE TITLE
Implement API to encrypt and decrypt files using password

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#991]
We need to be able to encrypt and decrypt files using passwords.
These functionality is needed before uploading files to CDN and after downloading them to RH.
Also we need to mask passwords being passed in log files

**Comment by Dilshat** [comment]
How to test:
1. Create file for testing `echo "hello" >> /tmp/test`
2. Run command `subutai file encrypt -s /tmp/test -p pwd123`
Output should contain path to encrypted file
3. Verify that file exists `ls /tmp/test.gpg`
4. Run command `subutai file decrypt -s /tmp/test.gpg -p pwd123`
Ouput should contain path to decrypted file
5. Verify that file exists `ls /tmp/test-decrypted`

**Comment by kurmanbekova6** [comment]
Followed the steps described above^^
Fixed in master
![Screenshot from 2019-04-10 11-47-50](https://user-images.githubusercontent.com/9501291/55854541-d3488000-5b86-11e9-8a1e-37a747b64fd2.png)
![Screenshot from 2019-04-10 11-49-49](https://user-images.githubusercontent.com/9501291/55854542-d3488000-5b86-11e9-9559-4c3478954485.png)
![Screenshot from 2019-04-10 11-50-17](https://user-images.githubusercontent.com/9501291/55854543-d3488000-5b86-11e9-89ab-1a9aa0dea4eb.png)
